### PR TITLE
fix tns external link in footer

### LINKED ISSUE #303: TNS link does not link to object
This was correctly done in alerce.online

### PR DESCRIPTION
**Pull request by JavierArredondo**
Close https://github.com/alercebroker/ztf_explorer/issues/303

### CODE REVIEW

File: components/misc/FooterTns.vue [hunk 1]
```diff
@@ -23,12 +23,13 @@ export default class FooterTns extends Vue {
   classified
 
   get url() {
-    if (this.tns_id) {
-      return 'https://wis-tns.weizmann.ac.il/object/' + this.tns_id
+    console.log(this.tnsId)
```
Comment (dirodriguezm) [inline components/misc/FooterTns.vue]: Remove console logs

Comment (JavierArredondo) [reply components/misc/FooterTns.vue]: done, ty

**Review by dirodriguezm — APPROVED** [review]
